export type View = 'dashboard' | 'incidents' | 'map' | 'team' | 'sites';
export type Status = 'NEW' | 'ASSIGNED' | 'IN_PROGRESS' | 'RESOLVED' | 'CLOSED';
export type Priority = 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
export type Category = 'Éclairage' | 'Plomberie' | 'Sécurité' | 'Mobilier' | 'Voirie' | 'Équipement' | 'Climatisation';

export type Audit = { id: string; label: string; actor: string; at: string; kind: 'created' | 'assignment' | 'status' | 'resolution' | 'closed' };
export type Comment = { id: string; author: string; body: string; at: string };
export type Incident = {
  id: string;
  title: string;
  description: string;
  category: Category;
  priority: Priority;
  status: Status;
  site: string;
  siteId: string;
  location: string;
  lat: number;
  lng: number;
  reporter: string;
  createdAt: string;
  updatedAt: string;
  assignee?: string;
  assignmentStatus?: 'PENDING_ACCEPTANCE' | 'ACCEPTED';
  resolutionText?: string;
  comments: Comment[];
  audit: Audit[];
};
export type Notice = { id: string; title: string; body: string; at: string; type: 'critical' | 'info' | 'success'; read: boolean; incidentId?: string };
export type Site = { id: string; name: string; address: string; active: boolean; incidents: number; color: string; lat: number; lng: number };
