CREATE TYPE "MembershipStatus" AS ENUM ('ACTIVE','SUSPENDED','REVOKED');
CREATE TYPE "IncidentStatus" AS ENUM ('NEW','ASSIGNED','IN_PROGRESS','RESOLVED','CLOSED');
CREATE TYPE "Priority" AS ENUM ('LOW','MEDIUM','HIGH','CRITICAL');
CREATE TYPE "AssignmentStatus" AS ENUM ('PENDING_ACCEPTANCE','ACCEPTED','REASSIGNMENT_REQUESTED','CLOSED');
CREATE TYPE "ProgressType" AS ENUM ('STARTED','ON_SITE','BLOCKED','UPDATE');
CREATE TYPE "UserRole" AS ENUM ('USER','RESPONSABLE','ADMINISTRATOR');
CREATE TABLE "Organization" ("id" UUID NOT NULL,"name" TEXT NOT NULL,"slug" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "Organization_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "Organization_slug_key" ON "Organization"("slug");
CREATE TABLE "User" ("id" UUID NOT NULL,"name" TEXT NOT NULL,"email" TEXT NOT NULL,"passwordHash" TEXT NOT NULL,"isVerified" BOOLEAN NOT NULL DEFAULT false,"verificationToken" TEXT,"verificationExpiry" TIMESTAMP(3),"resetToken" TEXT,"resetExpiry" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "User_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
CREATE TABLE "OrganizationMembership" ("id" UUID NOT NULL,"organizationId" UUID NOT NULL,"userId" UUID NOT NULL,"roles" "UserRole"[] NOT NULL,"status" "MembershipStatus" NOT NULL DEFAULT 'ACTIVE',"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "OrganizationMembership_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "OrganizationMembership_organizationId_userId_key" ON "OrganizationMembership"("organizationId","userId");
CREATE INDEX "OrganizationMembership_userId_status_idx" ON "OrganizationMembership"("userId","status");
CREATE TABLE "Site" ("id" UUID NOT NULL,"organizationId" UUID NOT NULL,"name" TEXT NOT NULL,"address" TEXT,"latitude" DOUBLE PRECISION NOT NULL,"longitude" DOUBLE PRECISION NOT NULL,"isActive" BOOLEAN NOT NULL DEFAULT true,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "Site_pkey" PRIMARY KEY ("id"));
CREATE INDEX "Site_organizationId_isActive_idx" ON "Site"("organizationId","isActive");
CREATE TABLE "ResponsableProfile" ("id" UUID NOT NULL,"organizationId" UUID NOT NULL,"userId" UUID NOT NULL,"isActive" BOOLEAN NOT NULL DEFAULT true,CONSTRAINT "ResponsableProfile_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "ResponsableProfile_organizationId_userId_key" ON "ResponsableProfile"("organizationId","userId");
CREATE TABLE "Specialty" ("id" UUID NOT NULL,"organizationId" UUID NOT NULL,"name" TEXT NOT NULL,CONSTRAINT "Specialty_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "Specialty_organizationId_name_key" ON "Specialty"("organizationId","name");
CREATE TABLE "ResponsableSpecialty" ("responsableProfileId" UUID NOT NULL,"specialtyId" UUID NOT NULL,CONSTRAINT "ResponsableSpecialty_pkey" PRIMARY KEY ("responsableProfileId","specialtyId"));
CREATE TABLE "ResponsableSite" ("responsableProfileId" UUID NOT NULL,"siteId" UUID NOT NULL,"isActive" BOOLEAN NOT NULL DEFAULT true,CONSTRAINT "ResponsableSite_pkey" PRIMARY KEY ("responsableProfileId","siteId"));
CREATE TABLE "Incident" ("id" UUID NOT NULL,"organizationId" UUID NOT NULL,"siteId" UUID NOT NULL,"reporterId" UUID NOT NULL,"title" TEXT NOT NULL,"description" TEXT NOT NULL,"category" TEXT NOT NULL,"priority" "Priority" NOT NULL,"latitude" DOUBLE PRECISION NOT NULL,"longitude" DOUBLE PRECISION NOT NULL,"status" "IncidentStatus" NOT NULL DEFAULT 'NEW',"resolutionText" TEXT,"version" INTEGER NOT NULL DEFAULT 1,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,"verifiedAt" TIMESTAMP(3),CONSTRAINT "Incident_pkey" PRIMARY KEY ("id"));
CREATE INDEX "Incident_organizationId_status_priority_idx" ON "Incident"("organizationId","status","priority");
CREATE INDEX "Incident_siteId_idx" ON "Incident"("siteId"); CREATE INDEX "Incident_reporterId_idx" ON "Incident"("reporterId");
CREATE TABLE "Assignment" ("id" UUID NOT NULL,"incidentId" UUID NOT NULL,"responsableProfileId" UUID NOT NULL,"assignedById" UUID NOT NULL,"status" "AssignmentStatus" NOT NULL DEFAULT 'PENDING_ACCEPTANCE',"isActive" BOOLEAN NOT NULL DEFAULT true,"reassignReason" TEXT,"startedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"endedAt" TIMESTAMP(3),CONSTRAINT "Assignment_pkey" PRIMARY KEY ("id"));
CREATE INDEX "Assignment_incidentId_isActive_idx" ON "Assignment"("incidentId","isActive"); CREATE INDEX "Assignment_responsableProfileId_idx" ON "Assignment"("responsableProfileId");
CREATE TABLE "ProgressUpdate" ("id" UUID NOT NULL,"incidentId" UUID NOT NULL,"authorId" UUID NOT NULL,"type" "ProgressType" NOT NULL,"note" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "ProgressUpdate_pkey" PRIMARY KEY ("id"));
CREATE INDEX "ProgressUpdate_incidentId_createdAt_idx" ON "ProgressUpdate"("incidentId","createdAt");
CREATE TABLE "Comment" ("id" UUID NOT NULL,"incidentId" UUID NOT NULL,"authorId" UUID NOT NULL,"body" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "Comment_pkey" PRIMARY KEY ("id"));
CREATE INDEX "Comment_incidentId_createdAt_idx" ON "Comment"("incidentId","createdAt");
CREATE TABLE "Attachment" ("id" UUID NOT NULL,"incidentId" UUID NOT NULL,"uploadedById" UUID NOT NULL,"originalName" TEXT NOT NULL,"mimeType" TEXT NOT NULL,"sizeBytes" INTEGER NOT NULL,"storageRef" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "Attachment_pkey" PRIMARY KEY ("id"));
CREATE INDEX "Attachment_incidentId_idx" ON "Attachment"("incidentId");
CREATE TABLE "AuditEvent" ("id" UUID NOT NULL,"incidentId" UUID,"actorId" UUID NOT NULL,"eventType" TEXT NOT NULL,"payload" JSONB NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "AuditEvent_pkey" PRIMARY KEY ("id"));
CREATE INDEX "AuditEvent_incidentId_createdAt_idx" ON "AuditEvent"("incidentId","createdAt"); CREATE INDEX "AuditEvent_actorId_idx" ON "AuditEvent"("actorId");
CREATE TABLE "Notification" ("id" UUID NOT NULL,"recipientId" UUID NOT NULL,"eventType" TEXT NOT NULL,"incidentId" UUID,"title" TEXT NOT NULL,"body" TEXT NOT NULL,"readAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "Notification_pkey" PRIMARY KEY ("id"));
CREATE INDEX "Notification_recipientId_readAt_idx" ON "Notification"("recipientId","readAt");
CREATE TABLE "Session" ("id" UUID NOT NULL,"userId" UUID NOT NULL,"organizationId" UUID NOT NULL,"tokenHash" TEXT NOT NULL,"expiresAt" TIMESTAMP(3) NOT NULL,"revokedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"lastUsedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "Session_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "Session_tokenHash_key" ON "Session"("tokenHash"); CREATE INDEX "Session_userId_revokedAt_idx" ON "Session"("userId","revokedAt"); CREATE INDEX "Session_organizationId_revokedAt_idx" ON "Session"("organizationId","revokedAt");
ALTER TABLE "OrganizationMembership" ADD CONSTRAINT "OrganizationMembership_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "OrganizationMembership" ADD CONSTRAINT "OrganizationMembership_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Site" ADD CONSTRAINT "Site_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ResponsableProfile" ADD CONSTRAINT "ResponsableProfile_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ResponsableProfile" ADD CONSTRAINT "ResponsableProfile_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Specialty" ADD CONSTRAINT "Specialty_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ResponsableSpecialty" ADD CONSTRAINT "ResponsableSpecialty_responsableProfileId_fkey" FOREIGN KEY ("responsableProfileId") REFERENCES "ResponsableProfile"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ResponsableSpecialty" ADD CONSTRAINT "ResponsableSpecialty_specialtyId_fkey" FOREIGN KEY ("specialtyId") REFERENCES "Specialty"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ResponsableSite" ADD CONSTRAINT "ResponsableSite_responsableProfileId_fkey" FOREIGN KEY ("responsableProfileId") REFERENCES "ResponsableProfile"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ResponsableSite" ADD CONSTRAINT "ResponsableSite_siteId_fkey" FOREIGN KEY ("siteId") REFERENCES "Site"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Incident" ADD CONSTRAINT "Incident_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Incident" ADD CONSTRAINT "Incident_siteId_fkey" FOREIGN KEY ("siteId") REFERENCES "Site"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Incident" ADD CONSTRAINT "Incident_reporterId_fkey" FOREIGN KEY ("reporterId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Assignment" ADD CONSTRAINT "Assignment_incidentId_fkey" FOREIGN KEY ("incidentId") REFERENCES "Incident"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Assignment" ADD CONSTRAINT "Assignment_responsableProfileId_fkey" FOREIGN KEY ("responsableProfileId") REFERENCES "ResponsableProfile"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Assignment" ADD CONSTRAINT "Assignment_assignedById_fkey" FOREIGN KEY ("assignedById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ProgressUpdate" ADD CONSTRAINT "ProgressUpdate_incidentId_fkey" FOREIGN KEY ("incidentId") REFERENCES "Incident"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ProgressUpdate" ADD CONSTRAINT "ProgressUpdate_authorId_fkey" FOREIGN KEY ("authorId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Comment" ADD CONSTRAINT "Comment_incidentId_fkey" FOREIGN KEY ("incidentId") REFERENCES "Incident"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Comment" ADD CONSTRAINT "Comment_authorId_fkey" FOREIGN KEY ("authorId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Attachment" ADD CONSTRAINT "Attachment_incidentId_fkey" FOREIGN KEY ("incidentId") REFERENCES "Incident"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "AuditEvent" ADD CONSTRAINT "AuditEvent_incidentId_fkey" FOREIGN KEY ("incidentId") REFERENCES "Incident"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "AuditEvent" ADD CONSTRAINT "AuditEvent_actorId_fkey" FOREIGN KEY ("actorId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Notification" ADD CONSTRAINT "Notification_recipientId_fkey" FOREIGN KEY ("recipientId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Notification" ADD CONSTRAINT "Notification_incidentId_fkey" FOREIGN KEY ("incidentId") REFERENCES "Incident"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Session" ADD CONSTRAINT "Session_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Session" ADD CONSTRAINT "Session_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
